name: "Remove Build Permissions Request"
description: Request to remove all build permissions for a specific user
title: "[PBPR] Remove permission "
labels: ["remove-permissions"]

body:
  - type: markdown
    attributes:
      value: |
        **Use this template to request the removal of all build permissions for a specific user.**
        Please fill out the required information below.

  - type: input
    attributes:
      label: GitHub Username
      description: The GitHub username of the person whose build permissions should be removed.
      placeholder: "example-username"
    validations:
      required: true

  - type: textarea
    attributes:
      label: Reason for Removal
      description: Provide a clear and concise reason for the removal request.
      placeholder: "The user no longer needs access to the build system."
    validations:
      required: true
