name: Handle Build Permission Request

on:
  issues:
    types: [opened]

jobs:
  process-issue:
    name: Process Build Permission Request
    runs-on: windows-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout Repo
        uses: actions/checkout@v3

      # Step 2: Run PowerShell Script
      - name: Run PowerShell Script to Process Issue
        run: |
          pwsh.exe -File .github/scripts/handle-request.ps1
        env:
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          ISSUE_TITLE: ${{ github.event.issue.title }}
          ORG_NAME_FOR_VALIDATION: "Dezone99"
          NAME_OF_REPO_CONTAINING_PERMISSION_REQUEST: ${{ github.event.repository.name }}"
          REPO_OWNER: ${{ github.event.repository.owner.login }}
          CREATOR_PROFILE_URL: ${{ github.event.issue.user.html_url }}
          GITHUB_TOKEN: ${{ secrets.WORK_FLOW_ACCESS_TOKEN }}
          NAME_OF_REPO_TO_SUBMIT_REQUEST: ${{ secrets.NAME_OF_REPO_TO_SUBMIT_REQUEST }}
          ISLOCAL: false
